# Generated by Django 6.0.4 on 2026-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Université', 'verbose_name_plural': 'Universités'},
        ),
        migrations.RemoveField(
            model_name='university',
            name='blockchain_private_key',
        ),
        migrations.RemoveField(
            model_name='university',
            name='blockchain_public_key',
        ),
        migrations.AddField(
            model_name='university',
            name='wallet_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de liaison MetaMask'),
        ),
        migrations.AlterField(
            model_name='university',
            name='blockchain_address',
            field=models.CharField(blank=True, help_text="Fournie par MetaMask côté frontend à l'inscription.", max_length=42, unique=True, verbose_name='Adresse Ethereum MetaMask (0x...)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='crypto_fingerprint',
            field=models.CharField(blank=True, max_length=64, verbose_name='Empreinte cryptographique SHA256'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name="Université vérifiée par l'admin"),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'université"),
        ),
        migrations.AlterField(
            model_name='university',
            name='private_key_pem',
            field=models.TextField(blank=True, verbose_name='Clé privée RSA (PEM)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='public_key_pem',
            field=models.TextField(blank=True, verbose_name='Clé publique RSA (PEM)'),
        ),
    ]
